@startuml
start
:User executes Add Command;


if () then ([User enters valid command])

    :Create the new Applicant with the attributes provided;

    if () then ([new Applicant already
    exists in LinkedOUT])

        :Error message displayed to User, showing
        existing applicant;

        stop

    else ([else])
    endif

    :Add the new Applicant into LinkedOUT;

    :Update GUI to display new applicant in list of applicants;
else ([else])

:Invalid command error message displayed to User;

endif
stop
@enduml
