@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Linkedout *-right-> "1" UniqueApplicantList
UniqueApplicantList -right-> Applicant

Applicant -up-> "*" Skill

Applicant *--> Name
Applicant *--> Phone
Applicant *--> Email
Applicant *--> Job
Applicant *--> Round
@enduml
