@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes edit command;
if () then ([valid index])
    if () then ([not duplicate applicant])
    :Display to user new \n applicant's details;
    :Update GUI to \ndisplay edited applicant \nin list of applicants ;
    else ([else])
    :Display error message to \nuser that arguments results \nin duplicated applicants;
    endif
else ([else])
:Display error message to user \nthat no applicant found;
endif

stop

@enduml
