@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyLinkedout" as ReadOnlyLinkedout
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class Linkedout
Class ModelManager
Class UserPrefs

Class UniqueApplicantList
Class Applicant
Class Job
Class Stage
Class Name
Class Phone
Class Skill

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Linkedout .up.|> ReadOnlyLinkedout

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyLinkedout
ModelManager -left-> "1" Linkedout
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Linkedout *--> "1" UniqueApplicantList
UniqueApplicantList --> "~* all" Applicant
Applicant *--> Name
Applicant *--> Phone
Applicant *--> Stage
Applicant *--> Job
Applicant *--> "*" Skill

Name -[hidden]right-> Phone
Phone -[hidden]right-> Job
Job -[hidden]right-> Stage

ModelManager -->"~* filtered" Applicant
@enduml
