@startuml
start
:User executes Search command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([user enters invalid command])
    :Display invalid command error message;
else ([else])
    if () then ([no applicant contains keyword and prefix specified])
    :No applicant found;
    else ([else])
    :Display applicants with partial matched keyword ;
endif
endif

stop
@enduml
