@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes view command;
if () then ([valid inputs])
    if () then ([valid name])
    :Display to user desired applicant's details;
    else ([else])
    :Display to user no applicant found;
    endif
else ([else])
:Error message to user signifying issue;
endif

stop

@enduml
